-- BidLens Fashion V3 additions. Monetary columns are integer cents; percentage rates are basis points.
ALTER TABLE "WatchlistItem" ADD COLUMN "plannedBid" INTEGER;
ALTER TABLE "WatchlistItem" ADD COLUMN "priority" TEXT NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE "WatchlistItem" ADD COLUMN "decisionDeadline" DATETIME;
CREATE TABLE "ResellerProfile" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT NOT NULL,"strategyName" TEXT NOT NULL DEFAULT 'Balanced reseller',"minimumProfitCents" INTEGER NOT NULL DEFAULT 10000,"minimumRoiBasisPoints" INTEGER NOT NULL DEFAULT 3000,"maximumPurchasePriceCents" INTEGER NOT NULL DEFAULT 100000,"maximumRiskLevel" TEXT NOT NULL DEFAULT 'MEDIUM',"preferredCategories" TEXT NOT NULL DEFAULT '[]',"preferredBrands" TEXT NOT NULL DEFAULT '[]',"excludedBrands" TEXT NOT NULL DEFAULT '[]',"preferredMarketplaces" TEXT NOT NULL DEFAULT '["eBay"]',"defaultBuyerPremiumBasisPoints" INTEGER NOT NULL DEFAULT 1800,"defaultSalesTaxBasisPoints" INTEGER NOT NULL DEFAULT 750,"defaultSellingFeeBasisPoints" INTEGER NOT NULL DEFAULT 1300,"defaultPaymentFeeBasisPoints" INTEGER NOT NULL DEFAULT 300,"defaultInboundShippingCents" INTEGER NOT NULL DEFAULT 0,"defaultOutboundShippingCents" INTEGER NOT NULL DEFAULT 1800,"defaultAuthenticationCostCents" INTEGER NOT NULL DEFAULT 3500,"defaultCleaningAllowanceCents" INTEGER NOT NULL DEFAULT 2000,"preferredResaleMarketplace" TEXT NOT NULL DEFAULT 'eBay',"targetHoldingPeriodDays" INTEGER NOT NULL DEFAULT 60,"accuracyToleranceBasisPoints" INTEGER NOT NULL DEFAULT 1500,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "ResellerProfile_userId_fkey" FOREIGN KEY("userId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "ResellerProfile_userId_key" ON "ResellerProfile"("userId");
CREATE TABLE "OpportunityDecision" ("id" TEXT NOT NULL PRIMARY KEY,"auctionListingId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'NEW',"marketOpportunityScore" INTEGER NOT NULL DEFAULT 0,"personalOpportunityScore" INTEGER NOT NULL DEFAULT 0,"positiveFactors" TEXT NOT NULL DEFAULT '[]',"negativeFactors" TEXT NOT NULL DEFAULT '[]',"recommendationReason" TEXT NOT NULL DEFAULT '',"recommendedNextAction" TEXT NOT NULL DEFAULT 'Review opportunity',"updatedAt" DATETIME NOT NULL,CONSTRAINT "OpportunityDecision_auctionListingId_fkey" FOREIGN KEY("auctionListingId") REFERENCES "AuctionListing"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "OpportunityDecision_auctionListingId_key" ON "OpportunityDecision"("auctionListingId"); CREATE INDEX "OpportunityDecision_status_personalOpportunityScore_idx" ON "OpportunityDecision"("status","personalOpportunityScore");
CREATE TABLE "DecisionRule" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,"conditions" TEXT NOT NULL,"action" TEXT NOT NULL,"message" TEXT NOT NULL,"priority" INTEGER NOT NULL DEFAULT 0,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "DecisionRule_userId_fkey" FOREIGN KEY("userId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE); CREATE INDEX "DecisionRule_userId_enabled_priority_idx" ON "DecisionRule"("userId","enabled","priority");
CREATE TABLE "InventoryItem" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT NOT NULL,"auctionListingId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'AWAITING_PAYMENT',"acquisitionDate" DATETIME,"purchasePriceCents" INTEGER NOT NULL DEFAULT 0,"buyerPremiumCents" INTEGER NOT NULL DEFAULT 0,"taxCents" INTEGER NOT NULL DEFAULT 0,"inboundShippingCents" INTEGER NOT NULL DEFAULT 0,"authenticationCostCents" INTEGER NOT NULL DEFAULT 0,"cleaningRepairCostCents" INTEGER NOT NULL DEFAULT 0,"otherAcquisitionCostsCents" INTEGER NOT NULL DEFAULT 0,"dateReceived" DATETIME,"conditionUponReceipt" TEXT,"authenticationResult" TEXT,"intendedResaleMarketplace" TEXT,"listingDate" DATETIME,"askingPriceCents" INTEGER,"acceptedOfferCents" INTEGER,"saleDate" DATETIME,"marketplaceFeeCents" INTEGER NOT NULL DEFAULT 0,"paymentFeeCents" INTEGER NOT NULL DEFAULT 0,"outboundShippingCents" INTEGER NOT NULL DEFAULT 0,"refundReturnCostsCents" INTEGER NOT NULL DEFAULT 0,"actualNetProceedsCents" INTEGER,"actualProfitCents" INTEGER,"actualRoiBasisPoints" INTEGER,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "InventoryItem_userId_fkey" FOREIGN KEY("userId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "InventoryItem_auctionListingId_fkey" FOREIGN KEY("auctionListingId") REFERENCES "AuctionListing"("id") ON DELETE CASCADE ON UPDATE CASCADE); CREATE UNIQUE INDEX "InventoryItem_auctionListingId_key" ON "InventoryItem"("auctionListingId"); CREATE INDEX "InventoryItem_userId_status_idx" ON "InventoryItem"("userId","status");
CREATE TABLE "SavedScenario" ("id" TEXT NOT NULL PRIMARY KEY,"userId" TEXT NOT NULL,"auctionListingId" TEXT NOT NULL,"name" TEXT NOT NULL,"resaleValueCents" INTEGER NOT NULL,"sellingFeeBasisPoints" INTEGER NOT NULL,"shippingCents" INTEGER NOT NULL,"cleaningRepairCents" INTEGER NOT NULL,"authenticationCents" INTEGER NOT NULL,"desiredProfitCents" INTEGER NOT NULL,"isActive" BOOLEAN NOT NULL DEFAULT false,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "SavedScenario_userId_fkey" FOREIGN KEY("userId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "SavedScenario_auctionListingId_fkey" FOREIGN KEY("auctionListingId") REFERENCES "AuctionListing"("id") ON DELETE CASCADE ON UPDATE CASCADE); CREATE UNIQUE INDEX "SavedScenario_userId_auctionListingId_name_key" ON "SavedScenario"("userId","auctionListingId","name"); CREATE INDEX "SavedScenario_userId_auctionListingId_idx" ON "SavedScenario"("userId","auctionListingId");
