import{detectLogin,extractListings}from'./extraction';import type{ExtractedEbthListing}from'./types';
let canceled=false,originalY=0,hidden:HTMLElement[]=[];
const count=()=>document.querySelectorAll('a[href*="/items/"]').length;
function extract():ExtractedEbthListing[]{const listings=extractListings(document,location.href);if(localStorage.getItem('bidlens:diagnostics')==='1')for(const listing of listings)console.debug('[BidLens extraction]',{method:listing.extractionMethod,rawBidText:listing.bidText,parsedBidCents:listing.currentBidCents,listingUrl:listing.listingUrl,warnings:listing.extractionWarnings});return listings}
async function prepare(){originalY=scrollY;canceled=false;return{pageUrl:location.href,pageTitle:document.title,viewport:{width:innerWidth,height:innerHeight},document:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight},initialListingCount:count(),loginPage:detectLogin(document.title,location.href,document.body.innerText.slice(0,3000)),hasLikelyCards:count()>0,warnings:[]}}
async function scrollPage(opts:{delay:number;max:number}){let stable=0,noNew=0,lastH=0,lastC=count(),attempts=0;while(attempts++<Math.min(80,opts.max)&&!canceled){scrollBy({top:innerHeight*.8,behavior:'smooth'});await new Promise(r=>setTimeout(r,Math.max(500,opts.delay)));const h=document.documentElement.scrollHeight,c=count();stable=h===lastH?stable+1:0;noNew=c===lastC?noNew+1:0;lastH=h;lastC=c;if(scrollY+innerHeight>=h-2||(stable>=4&&noNew>=4))break}await Promise.race([Promise.all([...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>new Promise<void>(r=>{i.addEventListener('load',()=>r(),{once:true});i.addEventListener('error',()=>r(),{once:true})}))),new Promise(r=>setTimeout(r,2000))]);return{listings:extract(),attempts,canceled,height:document.documentElement.scrollHeight,width:document.documentElement.scrollWidth,dpr:devicePixelRatio,viewportHeight:innerHeight}}
function hideFixed(){hidden=[];document.querySelectorAll<HTMLElement>('body *').forEach(e=>{const p=getComputedStyle(e).position;if((p==='fixed'||p==='sticky')&&e.getBoundingClientRect().height<innerHeight/2){e.dataset.bidlensVisibility=e.style.visibility;e.style.visibility='hidden';hidden.push(e)}})}
function restore(){hidden.forEach(e=>{e.style.visibility=e.dataset.bidlensVisibility||'';delete e.dataset.bidlensVisibility});hidden=[];scrollTo(0,originalY)}
chrome.runtime.onMessage.addListener((m:unknown,_s,respond)=>{const x=m as{type?:string;options?:{delay:number;max:number};y?:number};if(x.type==='PREPARE')prepare().then(respond);else if(x.type==='SCROLL')scrollPage(x.options!).then(respond);else if(x.type==='POSITION'){hideFixed();scrollTo(0,x.y||0);setTimeout(()=>respond({y:scrollY,width:innerWidth,height:innerHeight,dpr:devicePixelRatio}),180)}else if(x.type==='RESTORE'){restore();respond(true)}else if(x.type==='CANCEL'){canceled=true;restore();respond(true)}else return;return true});
