import{confidence,dedupe,detectLogin,itemId,normalizeListingUrl,parseCurrentBid,sensitive}from'./extraction';import type{ExtractedEbthListing}from'./types';
let canceled=false,originalY=0,hidden:HTMLElement[]=[];
const count=()=>document.querySelectorAll('a[href*="/items/"]').length;
function cardFor(a:HTMLAnchorElement){let node:HTMLElement=a;for(let i=0;i<5&&node.parentElement;i++,node=node.parentElement){const r=node.getBoundingClientRect();if(node.querySelector('img')&&r.width>140&&r.height>100&&r.height<1000)return node}return a}
function extract():ExtractedEbthListing[]{const source=location.href;return dedupe([...document.querySelectorAll<HTMLAnchorElement>('a[href*="/items/"]')].map((a,index)=>{const card=cardFor(a),raw=(card.innerText||'').replace(/\s+/g,' ').trim().slice(0,2000),warnings:string[]=[];const url=normalizeListingUrl(a.href,source),img=card.querySelector<HTMLImageElement>('img'),title=(a.getAttribute('aria-label')||a.textContent||img?.alt||'').trim().slice(0,300);const priceText=raw.match(/(?:current\s+bid|\bbid)\s*:?\s*\$[\d,.]+|\$[\d,.]+/i)?.[0],bid=priceText?parseCurrentBid(priceText):undefined;if(priceText&&bid==null)warnings.push('Bid text was ambiguous.');const end=raw.match(/(?:time left|ends?|closing)\s*:?\s*[^|]{1,100}/i)?.[0];if(end&&!/(?:UTC|GMT|ET|EST|EDT|CT|CST|CDT|MT|MST|MDT|PT|PST|PDT)/i.test(end))warnings.push('Closing time zone was not visible.');const safe=sensitive(raw)?undefined:raw;if(!safe)warnings.push('Sensitive-looking card text was omitted.');const r=card.getBoundingClientRect();const x:ExtractedEbthListing={id:itemId(url)||`ebth-${index}-${Math.round(r.top+scrollY)}`,sourcePageUrl:source,listingUrl:url,ebthItemId:itemId(url),title:title||undefined,imageUrl:img?.currentSrc||img?.src,currentBidCents:bid,priceText,timeRemaining:end,endingText:end,cardText:safe,boundingBox:{x:r.left+scrollX,y:r.top+scrollY,width:r.width,height:r.height},extractionConfidence:0,extractionWarnings:warnings};x.extractionConfidence=confidence(x);return x}))}
async function prepare(){originalY=scrollY;canceled=false;return{pageUrl:location.href,pageTitle:document.title,viewport:{width:innerWidth,height:innerHeight},document:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight},initialListingCount:count(),loginPage:detectLogin(document.title,location.href,document.body.innerText.slice(0,3000)),hasLikelyCards:count()>0,warnings:[]}}
async function scrollPage(opts:{delay:number;max:number}){let stable=0,noNew=0,lastH=0,lastC=count(),attempts=0;while(attempts++<Math.min(80,opts.max)&&!canceled){scrollBy({top:innerHeight*.8,behavior:'smooth'});await new Promise(r=>setTimeout(r,Math.max(500,opts.delay)));const h=document.documentElement.scrollHeight,c=count();stable=h===lastH?stable+1:0;noNew=c===lastC?noNew+1:0;lastH=h;lastC=c;if(scrollY+innerHeight>=h-2||(stable>=4&&noNew>=4))break}await Promise.race([Promise.all([...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>new Promise<void>(r=>{i.addEventListener('load',()=>r(),{once:true});i.addEventListener('error',()=>r(),{once:true})}))),new Promise(r=>setTimeout(r,2000))]);return{listings:extract(),attempts,canceled,height:document.documentElement.scrollHeight,width:document.documentElement.scrollWidth,dpr:devicePixelRatio,viewportHeight:innerHeight}}
function hideFixed(){hidden=[];document.querySelectorAll<HTMLElement>('body *').forEach(e=>{const p=getComputedStyle(e).position;if((p==='fixed'||p==='sticky')&&e.getBoundingClientRect().height<innerHeight/2){e.dataset.bidlensVisibility=e.style.visibility;e.style.visibility='hidden';hidden.push(e)}})}
function restore(){hidden.forEach(e=>{e.style.visibility=e.dataset.bidlensVisibility||'';delete e.dataset.bidlensVisibility});hidden=[];scrollTo(0,originalY)}
chrome.runtime.onMessage.addListener((m:unknown,_s,respond)=>{const x=m as{type?:string;options?:{delay:number;max:number};y?:number};if(x.type==='PREPARE')prepare().then(respond);else if(x.type==='SCROLL')scrollPage(x.options!).then(respond);else if(x.type==='POSITION'){hideFixed();scrollTo(0,x.y||0);setTimeout(()=>respond({y:scrollY,width:innerWidth,height:innerHeight,dpr:devicePixelRatio}),180)}else if(x.type==='RESTORE'){restore();respond(true)}else if(x.type==='CANCEL'){canceled=true;restore();respond(true)}else return;return true});
