import{readFileSync}from'node:fs';import{fileURLToPath}from'node:url';import{describe,expect,it}from'vitest';import{containerItemIds,extractListings,findListingContainer}from'./extraction';
class FakeElement{
 parentElement:FakeElement|null=null;children:FakeElement[]=[];currentSrc?:string;src?:string;href='';
 constructor(public tagName:string,public className='',public textContent='',public attrs:Record<string,string>={}){this.href=attrs.href||'';this.src=attrs.src}
 add(...children:FakeElement[]){for(const child of children){child.parentElement=this;this.children.push(child)}return this}
 get innerText():string{return[this.textContent,...this.children.map(x=>x.innerText)].filter(Boolean).join('\n')}
 getAttribute(name:string){return this.attrs[name]??null}
 private matches(selector:string){if(selector==='img')return this.tagName==='IMG';if(selector==='a[href*="/items/"]')return this.tagName==='A'&&this.href.includes('/items/');if(selector.startsWith('[')){const attr=selector.match(/^\[([^=*\]]+)/)?.[1];return!!attr&&this.attrs[attr]!=null}return false}
 querySelectorAll<T>(selector:string):T[]{return this.children.flatMap(x=>[...(x.matches(selector)?[x]:[]),...x.querySelectorAll<FakeElement>(selector)]) as T[]}
 querySelector<T>(selector:string){return(this.querySelectorAll(selector)[0]||null)as T|null}
}
const el=(tag:string,cls='',text='',attrs:Record<string,string>={})=>new FakeElement(tag.toUpperCase(),cls,text,attrs);
function row(id:string,title:string,bid?:string){const url=`https://www.ebth.com/items/${id}-${title.toLowerCase().replace(/\W+/g,'-')}`,image=el('div','image').add(el('a','', '',{href:url}).add(el('img','','',{src:`${id}.jpg`,alt:title}))),details=el('div','details').add(el('a','',title,{href:url}),el('span','',`ITMGU${id}`),el('span','','6 hours left')),bidColumn=el('div','bid').add(el('span','','Current Bid'),el('strong','',bid||''),el('span','','9 Bids'),el('a','','Place Bid',{href:`${url}#bid`}));return el('article','listing-row').add(image,details,bidColumn)}
function fixture(){const quartz=row('144001','Quartz Hololith Bangle','$20'),tory=row('144002','Tory Burch Ella Tote Bag in Black Nylon and Patent Leather','$45'),main=el('main','followed-items').add(quartz,tory),document={querySelectorAll:<T>(selector:string)=>main.querySelectorAll<T>(selector)};return{main,quartz,tory,document:document as unknown as Document}}
describe('EBTH followed-items fixture',()=>{it('contains the screenshot-style three-column markup',()=>{const html=readFileSync(fileURLToPath(new URL('./fixtures/ebth-followed-items.html',import.meta.url)),'utf8');expect(html.match(/class="listing-row"/g)).toHaveLength(2);expect(html).toContain('class="image"');expect(html).toContain('class="details"');expect(html).toContain('class="bid"')});it('selects complete rows and accepts repeated links to one item',()=>{const{main,quartz,tory}=fixture();for(const row of[quartz,tory]){const anchor=row.querySelectorAll<HTMLAnchorElement>('a[href*="/items/"]')[1],container=findListingContainer(anchor);expect(container).toBe(row);expect(container.tagName).toBe('ARTICLE');expect(container.querySelectorAll('a[href*="/items/"]')).toHaveLength(3);expect(containerItemIds(container)).toHaveLength(1)}expect(findListingContainer(quartz.querySelectorAll<HTMLAnchorElement>('a[href*="/items/"]')[0])).not.toBe(main)});it('rejects the shared ancestor containing two products and keeps bids associated',()=>{const{document}=fixture(),listings=extractListings(document,'https://www.ebth.com/users/followed_items');expect(listings).toHaveLength(2);expect(listings[0]).toMatchObject({title:'Quartz Hololith Bangle',currentBidCents:2000,bidCount:9,extractionMethod:'row-text:labeled-bid'});expect(listings[1]).toMatchObject({title:'Tory Burch Ella Tote Bag in Black Nylon and Patent Leather',currentBidCents:4500,bidCount:9})});it('leaves a missing bid undefined',()=>{const{document,quartz}=fixture();quartz.children[2]=el('div','bid','Auction pending');quartz.children[2].parentElement=quartz;expect(extractListings(document,'https://www.ebth.com').find(x=>x.id==='144001')?.currentBidCents).toBeUndefined()})});
