import{readFileSync}from'node:fs';import{fileURLToPath}from'node:url';import{describe,expect,it}from'vitest';import{containerItemIds,extractListings,findListingContainer}from'./extraction';
class FakeElement{
 parentElement:FakeElement|null=null;children:FakeElement[]=[];currentSrc?:string;src?:string;href='';
 constructor(public tagName:string,public className='',public ownContent='',public attrs:Record<string,string>={}){this.href=attrs.href||'';this.src=attrs.src}
 add(...children:FakeElement[]){for(const child of children){child.parentElement=this;this.children.push(child)}return this}
 get childNodes(){return this.ownContent?[{nodeType:3,textContent:this.ownContent}]:[]}
 get textContent():string{return this.ownContent+this.children.map(x=>x.textContent).join('')}
 get innerText():string{return this.textContent}
 getAttribute(name:string){return this.attrs[name]??null}
 private matches(selector:string){
  if(selector==='*')return true;if(selector==='img')return this.tagName==='IMG';if(selector==='a[href*="/items/"]')return this.tagName==='A'&&this.href.includes('/items/');
  const parts=selector.match(/^\[([^\]=*]+)(\*?=)?"?([^\]"]*)"?\](?:\[([^\]=]+)="([^"]+)"\])?$/);if(!parts)return false;
  const[,attr,operator,value,attr2,value2]=parts,actual=attr==='class'?this.className:this.attrs[attr];if(actual==null)return false;if(attr2&&this.attrs[attr2]!==value2)return false;return !operator||(operator==='='?actual===value:actual.includes(value));
 }
 querySelectorAll<T>(selector:string):T[]{return this.children.flatMap(x=>[...(x.matches(selector)?[x]:[]),...x.querySelectorAll<FakeElement>(selector)]) as T[]}
 querySelector<T>(selector:string){return(this.querySelectorAll(selector)[0]||null)as T|null}
}
const el=(tag:string,cls='',text='',attrs:Record<string,string>={})=>new FakeElement(tag.toUpperCase(),cls,text,attrs);
function row(id:string,title:string,bid?:string,count='9 Bids'){const url=`https://www.ebth.com/items/${id}-${title.toLowerCase().replace(/\W+/g,'-')}`,image=el('div','image').add(el('a','','',{href:url}).add(el('img','','',{src:`${id}.jpg`,alt:title}))),details=el('div','details').add(el('a','',title,{href:url,'aria-label':`View details for ${title}`}),el('span','',`ITMGU${id}`),el('span','','6 hours left')),bidColumn=el('div','bid-area').add(el('span','','Current Bid'),el('span','current-bid-amount',bid||''),el('span','bid-count',count),el('a','','Place Bid',{href:`${url}#bid`}));return el('article','listing-row').add(image,details,bidColumn)}
function fixture(){const quartz=row('144001','Quartz Hololith Bangle','$20'),tory=row('144002','Tory Burch Ella Tote Bag in Black Nylon and Patent Leather','$45'),main=el('main','followed-items').add(quartz,tory),document={querySelectorAll:<T>(selector:string)=>main.querySelectorAll<T>(selector)};return{main,quartz,tory,document:document as unknown as Document}}
describe('EBTH followed-items fixture',()=>{
 it('contains adjacent amount/count markup that concatenates in parent textContent',()=>{const html=readFileSync(fileURLToPath(new URL('./fixtures/ebth-followed-items.html',import.meta.url)),'utf8');expect(html.match(/class="listing-row"/g)).toHaveLength(3);expect(html).toContain('<span class="current-bid-amount">$20</span><span class="bid-count">9 Bids</span>');expect(html).toContain('<span class="current-bid-amount">$45</span><span class="bid-count">9 Bids</span>')});
 it('selects complete rows and accepts repeated links to one item',()=>{const{main,quartz,tory}=fixture();for(const row of[quartz,tory]){const anchor=row.querySelectorAll<HTMLAnchorElement>('a[href*="/items/"]')[1],container=findListingContainer(anchor);expect(container).toBe(row);expect(container.querySelectorAll('a[href*="/items/"]')).toHaveLength(3);expect(containerItemIds(container)).toHaveLength(1)}expect(findListingContainer(quartz.querySelectorAll<HTMLAnchorElement>('a[href*="/items/"]')[0])).not.toBe(main)});
 it('does not combine $20 or $45 with each listing bid count',()=>{const{document,quartz,tory}=fixture(),listings=extractListings(document,'https://www.ebth.com/users/followed_items');expect(quartz.children[2].textContent).toContain('Current Bid$209 Bids');expect(tory.children[2].textContent).toContain('Current Bid$459 Bids');expect(listings).toHaveLength(2);expect(listings[0]).toMatchObject({title:'Quartz Hololith Bangle',currentBidCents:2000,bidCount:9,extractionMethod:'selector:[class*="amount"]'});expect(listings[1]).toMatchObject({title:'Tory Burch Ella Tote Bag in Black Nylon and Patent Leather',currentBidCents:4500,bidCount:9});expect(listings[0].extractionWarnings[0]).toContain('Ignored concatenated row-text bid candidate "$209"');expect(listings[1].extractionWarnings[0]).toContain('Ignored concatenated row-text bid candidate "$459"')});
 it('does not turn $852 beside 2 Bids into $8522',()=>{const special=row('144003','Comma Decimal Test','$852','2 Bids'),document={querySelectorAll:<T>(selector:string)=>special.querySelectorAll<T>(selector)} as unknown as Document;expect(extractListings(document,'https://www.ebth.com')[0]).toMatchObject({currentBidCents:85200,bidCount:2})});
 it('supports commas and decimals',()=>{for(const[amount,value]of[['$1,250',125000],['$1,250.50',125050]]as const){const special=row('144004','Money Test',amount,'2 Bids'),document={querySelectorAll:<T>(selector:string)=>special.querySelectorAll<T>(selector)} as unknown as Document;expect(extractListings(document,'https://www.ebth.com')[0].currentBidCents).toBe(value)}});
 it('leaves a missing bid undefined rather than zero',()=>{const{document,quartz}=fixture();quartz.children[2]=el('div','bid','Auction pending');quartz.children[2].parentElement=quartz;expect(extractListings(document,'https://www.ebth.com').find(x=>x.id==='144001')?.currentBidCents).toBeUndefined()});
});
