import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
const signatures={'image/jpeg':b=>b[0]===255&&b[1]===216&&b[2]===255,'image/png':b=>b.length>=8&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),'image/webp':b=>b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP','image/heic':b=>b.toString('ascii',4,8)==='ftyp'&&/^(heic|heix|hevc|hevx|mif1|msf1)$/.test(b.toString('ascii',8,12))};
export const detectImageType=b=>Object.entries(signatures).find(([,test])=>test(b))?.[0];
export class MobileImportStore{constructor({ttlMinutes=Number(process.env.MOBILE_IMPORT_TTL_MINUTES)||60,dir=path.join(os.tmpdir(),'bidlens-mobile-imports'),now=()=>Date.now()}={}){this.ttlMs=ttlMinutes*60000;this.dir=dir;this.now=now;this.records=new Map()}async init(){await fs.mkdir(this.dir,{recursive:true,mode:0o700})}async put(buffer,metadata={}){await this.init();const token=crypto.randomBytes(32).toString('base64url'),filename=crypto.randomBytes(32).toString('hex'),expiresAt=this.now()+this.ttlMs;await fs.writeFile(path.join(this.dir,filename),buffer,{mode:0o600,flag:'wx'});this.records.set(token,{filename,expiresAt,metadata});return{token,expiresAt}}async take(token){const r=this.records.get(token);if(!r)return{status:'missing'};this.records.delete(token);const file=path.join(this.dir,r.filename);if(r.expiresAt<=this.now()){await fs.rm(file,{force:true});return{status:'expired'}}try{const buffer=await fs.readFile(file);await fs.rm(file,{force:true});return{status:'ok',buffer,...r}}catch{return{status:'missing'}}}async cleanup(){for(const[token,r]of this.records)if(r.expiresAt<=this.now()){this.records.delete(token);await fs.rm(path.join(this.dir,r.filename),{force:true})}}}
const safe=(v,max)=>typeof v==='string'?v.replace(/[\r\n]/g,' ').slice(0,max):'';
export function parseMultipart(buffer,contentType){const boundary=/boundary=(?:"([^"]+)"|([^;]+))/.exec(contentType)?.slice(1).find(Boolean);if(!boundary)throw Object.assign(new Error('Invalid multipart form.'),{status:400});const marker=Buffer.from(`--${boundary}`),out={fields:{}};let start=buffer.indexOf(marker)+marker.length;while(start>=marker.length){start+=2;const end=buffer.indexOf(marker,start);if(end<0)break;const part=buffer.subarray(start,end-2),split=part.indexOf(Buffer.from('\r\n\r\n'));if(split>0){const headers=part.subarray(0,split).toString('latin1'),data=part.subarray(split+4),name=/name="([^"]+)"/.exec(headers)?.[1],filename=/filename="([^"]*)"/.exec(headers)?.[1];if(name==='image'&&filename)out.image=data;else if(name)out.fields[name]=data.toString('utf8')}start=end+marker.length}return out}
export function installMobileImportRoutes(app,{store=new MobileImportStore(),env=process.env}={}){const max=Number(env.MOBILE_IMPORT_MAX_BYTES)||10485760;const timer=setInterval(()=>store.cleanup().catch(()=>{}),300000);timer.unref();app.post('/api/mobile-import',express.raw({type:'multipart/form-data',limit:max+65536}),async(req,res,next)=>{try{const {image,fields}=parseMultipart(req.body,req.get('content-type')||'');if(!image)return res.status(400).json({error:'Add one image in the image form field.',code:'IMAGE_REQUIRED'});if(image.length>max)return res.status(413).json({error:'Image exceeds the 10 MB limit.',code:'IMAGE_TOO_LARGE'});const type=detectImageType(image);if(!type)return res.status(415).json({error:'The uploaded file is not a supported image.',code:'INVALID_IMAGE'});const metadata={sourceUrl:safe(fields.sourceUrl,500),sourceTitle:safe(fields.sourceTitle,200),currentBidText:safe(fields.currentBidText,80),type};const{token,expiresAt}=await store.put(image,metadata),publicUrl=env.PUBLIC_BIDLENS_URL||'https://brandinealnku.github.io/bidlens-fashion/';res.status(201).json({importToken:token,openUrl:`${publicUrl}${publicUrl.includes('?')?'&':'?'}mobileImport=${token}`,expiresAt:new Date(expiresAt).toISOString()})}catch(e){next(e)}});app.get('/api/mobile-import/:token',async(req,res,next)=>{try{if(!/^[\w-]{40,100}$/.test(req.params.token))return res.status(404).json({error:'Import not found.',code:'IMPORT_NOT_FOUND'});const x=await store.take(req.params.token);if(x.status==='expired')return res.status(410).json({error:'This import expired.',code:'IMPORT_EXPIRED'});if(x.status!=='ok')return res.status(404).json({error:'This import was already used or does not exist.',code:'IMPORT_NOT_FOUND'});res.set({'Content-Type':x.metadata.type,'Cache-Control':'no-store','X-BidLens-Source-Title':encodeURIComponent(x.metadata.sourceTitle),'X-BidLens-Current-Bid':encodeURIComponent(x.metadata.currentBidText),'X-BidLens-Source-Url':encodeURIComponent(x.metadata.sourceUrl),'Access-Control-Expose-Headers':'Content-Type,X-BidLens-Source-Title,X-BidLens-Current-Bid,X-BidLens-Source-Url'}).send(x.buffer)}catch(e){next(e)}});return store}
