import { z } from 'zod';
import { categories } from '@/lib/validation/fashion';

export const listingInput = z.object({
  sourceUrl: z.string().url().startsWith('https://').optional().nullable(),
  title: z.string().min(2).max(200),
  description: z.string().max(10000).default(''),
  category: z.enum(categories),
  currentBid: z.number().int().nonnegative(),
  currency: z.string().length(3).default('USD'),
  buyerPremiumType: z.enum(['PERCENT', 'FIXED']).default('PERCENT'),
  buyerPremiumValue: z.number().int().nonnegative(),
  taxRate: z.number().int().min(0).max(10000),
  inboundShippingCost: z.number().int().nonnegative().default(0),
  pickupCost: z.number().int().nonnegative().default(0),
  auctionEndAt: z.coerce.date().optional().nullable(),
  conditionText: z.string().max(4000).optional().nullable(),
});
export const assumptionsInput = z.object({
  taxHammer: z.boolean(),
  taxPremium: z.boolean(),
  authentication: z.number().int().nonnegative(),
  cleaning: z.number().int().nonnegative(),
  repair: z.number().int().nonnegative(),
  otherAcquisition: z.number().int().nonnegative(),
  sellingFeeBps: z.number().int().min(0).max(10000),
  paymentFeeBps: z.number().int().min(0).max(10000),
  promotional: z.number().int().nonnegative(),
  outbound: z.number().int().nonnegative(),
  packaging: z.number().int().nonnegative(),
  returnRiskBps: z.number().int().min(0).max(10000),
  otherSelling: z.number().int().nonnegative(),
  minimumProfit: z.number().int().nonnegative(),
  minimumRoiBps: z.number().int().min(0),
  bidIncrement: z.number().int().positive(),
  notes: z.string().max(4000).optional().nullable(),
});
export const comparableInput = z.object({
  marketplace: z.string().min(1),
  comparableStatus: z.enum([
    'SOLD_VERIFIED',
    'SOLD_USER_REPORTED',
    'ACTIVE_LISTING',
    'ESTIMATED',
    'UNKNOWN',
  ]),
  title: z.string().min(2),
  sourceUrl: z.string().url().optional().nullable(),
  imageUrl: z.string().url().optional().nullable(),
  price: z.number().int().positive(),
  shippingPrice: z.number().int().nonnegative().default(0),
  currency: z.string().length(3).default('USD'),
  condition: z.string().optional().nullable(),
  size: z.string().optional().nullable(),
  color: z.string().optional().nullable(),
  material: z.string().optional().nullable(),
  includedItems: z.string().optional().nullable(),
  soldOrListedAt: z.coerce.date().optional().nullable(),
  userNotes: z.string().max(2000).optional().nullable(),
});
export const settingsInput = z.object({
  preferredCurrency: z.string().length(3),
  defaultTaxRate: z.number().int().min(0).max(10000),
  defaultBuyerPremiumPercent: z.number().int().min(0).max(10000),
  defaultSellingFeePercent: z.number().int().min(0).max(10000),
  defaultPaymentFeePercent: z.number().int().min(0).max(10000),
  defaultOutboundShipping: z.number().int().nonnegative(),
  defaultPackagingCost: z.number().int().nonnegative(),
  defaultCleaningAllowance: z.number().int().nonnegative(),
  defaultRepairAllowance: z.number().int().nonnegative(),
  defaultAuthenticationAllowance: z.number().int().nonnegative(),
  defaultReturnRiskPercent: z.number().int().min(0).max(10000),
  minimumRequiredProfit: z.number().int().nonnegative(),
  minimumRequiredROI: z.number().int().nonnegative(),
  buyThresholdScore: z.number().int().min(0).max(100),
  reviewThresholdScore: z.number().int().min(0).max(100),
  preferredMarketplaces: z.string(),
  timezone: z.string().min(1),
  demoMode: z.boolean(),
});
