import { z } from 'zod';
export const categories = [
  'HANDBAG',
  'WALLET',
  'SMALL_LEATHER_GOOD',
  'SHOE',
  'BOOT',
  'COAT',
  'JACKET',
  'DRESS',
  'TOP',
  'BOTTOM',
  'SCARF',
  'BELT',
  'ACCESSORY',
  'COSTUME_JEWELRY',
  'FASHION_WATCH',
  'VINTAGE_APPAREL',
  'OTHER_FASHION',
  'UNSUPPORTED',
] as const;
const candidate = z.object({
  brand: z.string().nullable(),
  model: z.string().nullable(),
  productLine: z.string().nullable(),
  category: z.enum(categories),
  color: z.array(z.string()),
  material: z.array(z.string()),
  size: z.string().nullable(),
  estimatedEra: z.string().nullable(),
  confidence: z.number().min(0).max(1),
  evidence: z.array(z.string()),
  conflictingEvidence: z.array(z.string()),
  searchQueries: z.array(z.string()),
});
export const fashionAnalysisSchema = z.object({
  category: z.enum(categories),
  brand: z.string().nullable(),
  suspectedModel: z.string().nullable(),
  productLine: z.string().nullable(),
  styleNumber: z.string().nullable(),
  serialOrDateCode: z.string().nullable(),
  color: z.array(z.string()),
  material: z.array(z.string()),
  size: z.string().nullable(),
  dimensions: z
    .object({
      width: z.number().positive().optional(),
      height: z.number().positive().optional(),
      depth: z.number().positive().optional(),
      strapDrop: z.number().positive().optional(),
      heelHeight: z.number().positive().optional(),
      unit: z.enum(['in', 'cm']).optional(),
    })
    .nullable(),
  estimatedEra: z.string().nullable(),
  genderMarket: z.string().nullable(),
  conditionGrade: z.enum([
    'NEW_WITH_TAGS',
    'LIKE_NEW',
    'EXCELLENT',
    'GOOD',
    'FAIR',
    'POOR',
    'UNKNOWN',
  ]),
  visibleDamage: z.array(z.string()),
  includedItems: z.array(z.string()),
  visibleMarkings: z.array(z.string()),
  evidence: z.array(z.string()),
  conflictingEvidence: z.array(z.string()),
  identificationConfidence: z.number().min(0).max(1),
  authenticityRiskLevel: z.enum([
    'LOW',
    'MODERATE',
    'HIGH',
    'INSUFFICIENT_EVIDENCE',
  ]),
  authenticityConfidence: z.number().min(0).max(1).nullable(),
  authenticationRecommended: z.boolean(),
  searchQueries: z.array(z.string()),
  candidates: z.array(candidate).max(3),
});
export type FashionProductAnalysis = z.infer<typeof fashionAnalysisSchema>;
