import type{OcrLine,OcrProgress,OcrResult,RescanTarget}from'./types';import{prepareImage}from'./imagePreprocessing';import{parseEbthScreenshot}from'../parsers/ebthScreenshotParser';
type Worker={recognize:(image:Blob)=>Promise<{data:{text:string;lines?:Array<{text:string;confidence:number;name?:string;type?:string;bbox:{x0:number;y0:number;x1:number;y1:number}}>}}>;terminate:()=>Promise<unknown>};
let workerPromise:Promise<Worker>|undefined;
async function worker(progress:(value:OcrProgress)=>void){if(!workerPromise)workerPromise=import('tesseract.js').then(({createWorker})=>createWorker('eng',1,{logger:event=>{if(event.status==='recognizing text')progress({stage:'Reading screenshot',progress:event.progress})}}) as Promise<Worker>);return workerPromise}
export async function terminateOcrWorker(){if(workerPromise){const active=await workerPromise.catch(()=>undefined);await active?.terminate();workerPromise=undefined}}
export async function recognizeScreenshot(source:Blob|string,progress:(value:OcrProgress)=>void,signal?:AbortSignal,crop?:{x:number;y:number;width:number;height:number},target:RescanTarget='full'):Promise<OcrResult>{
 progress({stage:'Preparing image',progress:0});const prepared=await prepareImage(source,crop);if(signal?.aborted){prepared.dispose();throw new DOMException('Canceled','AbortError')}
 try{const active=await worker(progress);if(signal?.aborted)throw new DOMException('Canceled','AbortError');const {data}=await active.recognize(prepared.blob);if(signal?.aborted)throw new DOMException('Canceled','AbortError');progress({stage:'Finding listing details',progress:.95});const lines:OcrLine[]=(data.lines||[]).filter(x=>x.text.trim()).map(x=>({text:x.text.trim(),confidence:x.confidence,boundingBox:{x:x.bbox.x0,y:x.bbox.y0,width:x.bbox.x1-x.bbox.x0,height:x.bbox.y1-x.bbox.y0}}));const parsed=parseEbthScreenshot(lines,prepared.height);if(target==='title')parsed.parsed={title:parsed.parsed.title,brand:parsed.parsed.brand};if(target==='bid')parsed.parsed={currentBidCents:parsed.parsed.currentBidCents,bidCount:parsed.parsed.bidCount};progress({stage:'Complete',progress:1});return parsed}finally{prepared.dispose()}
}
