export const opportunities = [
  {
    id: 'handbag',
    icon: '👜',
    brand: 'Maison Aurelia',
    model: 'Marais leather satchel',
    cat: 'Handbag',
    bid: 180,
    max: 310,
    resale: 620,
    profit: 247,
    roi: 74,
    confidence: 91,
    rec: 'BUY',
  },
  {
    id: 'shoes',
    icon: '👠',
    brand: 'Atelier No. 8',
    model: 'Suede block-heel pumps',
    cat: 'Shoes',
    bid: 95,
    max: 135,
    resale: 285,
    profit: 108,
    roi: 52,
    confidence: 78,
    rec: 'REVIEW',
  },
  {
    id: 'coat',
    icon: '🧥',
    brand: 'North & Finch',
    model: 'Double-face wool coat',
    cat: 'Coat',
    bid: 120,
    max: 155,
    resale: 390,
    profit: 132,
    roi: 50,
    confidence: 68,
    rec: 'REVIEW',
  },
  {
    id: 'jacket',
    icon: '🧥',
    brand: 'Ridge Heritage',
    model: '1990s leather jacket',
    cat: 'Vintage apparel',
    bid: 80,
    max: 165,
    resale: 340,
    profit: 141,
    roi: 67,
    confidence: 83,
    rec: 'BUY',
  },
  {
    id: 'suspicious',
    icon: '👜',
    brand: 'Unknown luxury',
    model: 'Monogram top-handle',
    cat: 'Handbag',
    bid: 420,
    max: 0,
    resale: 0,
    profit: -558,
    roi: -100,
    confidence: 31,
    rec: 'PASS',
  },
  {
    id: 'mixed',
    icon: '👕',
    brand: 'Mixed lot',
    model: 'Assorted casual tops',
    cat: 'Other fashion',
    bid: 70,
    max: 25,
    resale: 90,
    profit: -42,
    roi: -38,
    confidence: 54,
    rec: 'PASS',
  },
] as const;
export const usd = (n: number) =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(n);
