import React,{useEffect,useRef,useState}from'react';import{recognizeScreenshot,terminateOcrWorker}from'../ocr/ocrEngine';import type{OcrProgress,OcrResult,ParsedScreenshot,RescanTarget}from'../ocr/types';import{OcrReviewCard}from'./OcrReviewCard';
type Fields={brand?:string;title:string;currentBidCents:number;bidCount?:number;shippingCents:number;condition:string};
export function ScreenshotAnalysis({image,fields,onParsed,onEdit,onReplace,onDelete}: {image:string;fields:Fields;onParsed:(parsed:ParsedScreenshot,result:OcrResult)=>void;onEdit:(key:keyof Fields,value:string|number|undefined)=>void;onReplace:()=>void;onDelete:()=>void}){
 const[result,setResult]=useState<OcrResult>(),[status,setStatus]=useState<OcrProgress>(),[error,setError]=useState(''),[rotation,setRotation]=useState(0),[cropOpen,setCropOpen]=useState(false),[crop,setCrop]=useState({left:0,top:0,width:100,height:100}),controller=useRef<AbortController|undefined>(undefined),review=useRef<HTMLElement>(null);
 const scan=async(target:RescanTarget='full')=>{controller.current?.abort();const next=new AbortController;controller.current=next;setError('');setStatus({stage:'Preparing image',progress:0});try{let region; if(target!=='full'||cropOpen){const probe=new Image();probe.src=image;await probe.decode();region={x:probe.naturalWidth*crop.left/100,y:probe.naturalHeight*crop.top/100,width:probe.naturalWidth*crop.width/100,height:probe.naturalHeight*crop.height/100}}const found=await recognizeScreenshot(image,setStatus,next.signal,region,target);setResult(previous=>target==='full'||!previous?found:{...previous,rawText:`${previous.rawText}\n${found.rawText}`,parsed:{...previous.parsed,...found.parsed},confidence:{...previous.confidence,...found.confidence}});onParsed(found.parsed,found);requestAnimationFrame(()=>review.current?.scrollIntoView({behavior:'smooth',block:'nearest'}))}catch(e){if((e as Error).name!=='AbortError')setError('We could not confidently read every detail. You can retry, crop and rescan, or enter it manually.')}finally{if(!next.signal.aborted)setStatus(s=>s?.stage==='Complete'?s:undefined)}};
 useEffect(()=>{scan();return()=>controller.current?.abort()},[image]);useEffect(()=>()=>{terminateOcrWorker().catch(()=>{})},[]);
 const cancel=()=>{controller.current?.abort();setStatus(undefined);setError('Scan canceled. Your screenshot and manual details are preserved.')};
 return <><div className="preview"><img src={image} style={{transform:`rotate(${rotation}deg)`}} alt="Auction screenshot"/><div className="image-actions"><button onClick={()=>setCropOpen(x=>!x)}>Crop</button><button onClick={onReplace}>Replace</button><button onClick={()=>setRotation(x=>x+90)}>Rotate</button><button className="danger" onClick={onDelete}>Delete</button></div>{status&&status.stage!=='Complete'&&<div className="ocr-progress" aria-live="polite"><b>{status.stage}</b><progress value={status.progress??undefined} max="1"/><span>{status.progress!==undefined?`${Math.round(status.progress*100)}%`:''}</span><button onClick={cancel}>Cancel</button></div>}</div><p className="local-privacy">Screenshot text is read on this device and is not sent to an AI provider.</p>{cropOpen&&<div className="crop-panel"><p>Choose the region using percentages, then rescan only what you need.</p>{(['left','top','width','height'] as const).map(key=><label key={key}>{key}<input type="range" min="0" max="100" value={crop[key]} onChange={e=>setCrop(x=>({...x,[key]:Number(e.target.value)}))}/></label>)}<div><button onClick={()=>scan('title')}>Rescan title</button><button onClick={()=>scan('bid')}>Rescan bid</button><button onClick={()=>scan('full')}>Rescan full screenshot</button></div></div>}{error&&<div className="ocr-error" role="alert"><p>{error}</p><button onClick={()=>scan()}>Retry</button><button onClick={()=>setCropOpen(true)}>Crop and rescan</button></div>}{result&&<div ref={review as React.RefObject<HTMLDivElement>}><OcrReviewCard result={result} fields={fields} onChange={onEdit} onAccept={()=>setCropOpen(false)} onScanAgain={()=>scan()}/></div>}</>
}
