import type{ComparableEvidence,ComparableSearchResult,EvidenceValuation,RealizationFactors,ResearchableProduct}from'./types';

const noise=/\b(?:view details for|current bid|place bid|\d*\s*bids?|\d+\s*hours? left|item\s*#?\w+|lot\s*#?\w+|estate collection(?: of [\w ]+)?)\b/gi;
const stop=new Set(['the','and','with','for','from','this','that','in','of','a','an','at','on','ebth']);
export const cleanTitle=(title:string)=>title.replace(noise,' ').replace(/[|•—]+/g,' ').replace(/\s+/g,' ').trim();
const tokens=(value?:string)=>[...new Set((value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(' ').filter(x=>x.length>1&&!stop.has(x)))];
const phrase=(...parts:(string|undefined)[])=>[...new Set(parts.flatMap(tokens))].slice(0,8).join(' ');
export function generateSearchQueries(product:ResearchableProduct){const title=cleanTitle(product.title);return[phrase(product.brand,product.model,product.productType),phrase(product.brand,title),phrase(product.category,product.material,product.color,product.productType)].filter((q,i,a)=>q.length>2&&a.indexOf(q)===i).slice(0,3)}
const hasPhrase=(text:string,value?:string)=>!!value&&tokens(value).every(x=>tokens(text).includes(x));
const contradictions=[['replica',30],['inspired',25],['faux',20],['damaged',15],['parts only',35],['empty box',40],['dust bag only',40],['bundle',15],['lot of',15]] as const;
export function scoreComparable(product:ResearchableProduct,evidence:Pick<ComparableEvidence,'title'|'brand'|'condition'|'material'|'model'|'imageSearchMatch'>){const hay=`${evidence.title} ${evidence.brand||''} ${evidence.model||''} ${evidence.material||''}`.toLowerCase(),reasons:string[]=[],warnings:string[]=[];let score=0;
 const add=(ok:boolean,points:number,label:string)=>{if(ok){score+=points;reasons.push(label)}};
 add(hasPhrase(hay,product.brand),25,'Exact brand match');add(hasPhrase(hay,product.model),25,'Model or collection match');add(hasPhrase(hay,product.productType),15,'Product type match');add(hasPhrase(hay,product.material),10,'Material match');add(hasPhrase(hay,product.color),5,'Color match');add(!product.condition||!evidence.condition||tokens(product.condition).some(x=>tokens(evidence.condition).includes(x)),5,'Condition is compatible');
 const wanted=tokens(cleanTitle(product.title)),got=tokens(evidence.title),similarity=wanted.length?wanted.filter(x=>got.includes(x)).length/wanted.length:0;score+=Math.round(similarity*10);if(similarity>=.5)reasons.push('Strong title-token similarity');if(evidence.imageSearchMatch){score+=5;reasons.push('Image-search support (visual similarity is not proof of identity)')}
 for(const[p,penalty]of contradictions)if(hay.includes(p)){score-=penalty;warnings.push(`Contradictory term: ${p}`)}if(product.model&&evidence.model&&!hasPhrase(evidence.model,product.model)){score-=25;warnings.push('Materially different model')}
 return{matchScore:Math.max(0,Math.min(100,score)),matchReasons:reasons,mismatchWarnings:warnings}}
export const DEFAULT_REALIZATION_FACTORS:RealizationFactors={conservative:.65,expected:.75,optimistic:.9};
const median=(x:number[])=>{const a=[...x].sort((a,b)=>a-b),m=Math.floor(a.length/2);return a.length%2?a[m]:Math.round((a[m-1]+a[m])/2)};
const weightedMedian=(rows:{value:number;weight:number}[])=>{const a=[...rows].sort((x,y)=>x.value-y.value),half=a.reduce((s,x)=>s+x.weight,0)/2;let n=0;for(const x of a){n+=x.weight;if(n>=half)return x.value}return a.at(-1)!.value};
export function valueApprovedEvidence(productId:string,evidence:ComparableEvidence[],factors=DEFAULT_REALIZATION_FACTORS):EvidenceValuation{const approved=evidence.filter(x=>x.productId===productId&&x.status==='approved'&&x.matchScore>=40&&x.priceEstablished!==false),warnings:string[]=[];if(!approved.length)return{productId,conservativeCents:0,expectedCents:0,optimisticCents:0,confidence:0,activeComparableCount:0,soldComparableCount:0,evidenceCount:0,medianCents:null,weightedCentralCents:null,priceRangeCents:null,outlierWarnings:['No approved comparable evidence.'],excludedEvidenceIds:[],source:'insufficient-evidence'};
 const raw=approved.map(x=>x.totalPriceCents),med=median(raw),deviations=raw.map(x=>Math.abs(x-med)),mad=median(deviations),excluded=new Set<string>();approved.forEach(x=>{if((mad>0&&Math.abs(x.totalPriceCents-med)>3*mad)||(mad===0&&x.totalPriceCents>med*2)){excluded.add(x.id);warnings.push(`${x.title}: price is outside the median absolute deviation range.`)}if(!x.condition)warnings.push(`${x.title}: condition is missing.`);if((x.shippingCents||0)>x.itemPriceCents*.4)warnings.push(`${x.title}: shipping is unusually high.`);if(x.mismatchWarnings.length)warnings.push(`${x.title}: ${x.mismatchWarnings.join(', ')}.`)});if(approved.length===1)warnings.push('Only one approved comparable exists.');
 const usable=approved.filter(x=>!excluded.has(x.id));if(!usable.length)return{productId,conservativeCents:0,expectedCents:0,optimisticCents:0,confidence:10,activeComparableCount:approved.filter(x=>x.evidenceType==='active-listing').length,soldComparableCount:approved.filter(x=>x.evidenceType==='sold-listing'||x.evidenceType==='user-entered').length,evidenceCount:approved.length,medianCents:med,weightedCentralCents:null,priceRangeCents:[Math.min(...raw),Math.max(...raw)],outlierWarnings:warnings,excludedEvidenceIds:[...excluded],source:'insufficient-evidence'};
 const rows=(factor:keyof RealizationFactors)=>usable.map(x=>{const active=x.evidenceType==='active-listing',base=x.evidenceType==='sold-listing'?1:x.evidenceType==='user-entered' ? .85 : active ? (x.matchScore>=75 ? .5 : .3) : .15;return{value:Math.round(x.totalPriceCents*(active?factors[factor]:1)),weight:base*x.matchScore/100}}),expected=weightedMedian(rows('expected'));const active=approved.filter(x=>x.evidenceType==='active-listing').length,sold=approved.filter(x=>x.evidenceType==='sold-listing'||x.evidenceType==='user-entered').length;
 return{productId,conservativeCents:weightedMedian(rows('conservative')),expectedCents:expected,optimisticCents:weightedMedian(rows('optimistic')),confidence:Math.min(95,Math.round(35+usable.length*10+(sold?20:0)+usable.reduce((s,x)=>s+x.matchScore,0)/usable.length*.2)),activeComparableCount:active,soldComparableCount:sold,evidenceCount:approved.length,medianCents:med,weightedCentralCents:expected,priceRangeCents:[Math.min(...raw),Math.max(...raw)],outlierWarnings:warnings,excludedEvidenceIds:[...excluded],source:'evidence'} }
export function createManualComparable(productId:string,input:{marketplace:string;title:string;soldPriceCents:number;shippingCents:number;url:string;soldDate:string;condition:string;notes?:string;imageUrl?:string}):ComparableEvidence{if(!input.marketplace||!input.title||!input.url||!input.soldDate||!input.condition||!Number.isInteger(input.soldPriceCents)||!Number.isInteger(input.shippingCents))throw new Error('Complete every required manual comparable field with integer-cent prices.');return{id:`manual-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,productId,provider:'manual',evidenceType:'user-entered',title:input.title,url:input.url,imageUrl:input.imageUrl,itemPriceCents:input.soldPriceCents,shippingCents:input.shippingCents,totalPriceCents:input.soldPriceCents+input.shippingCents,condition:input.condition,matchScore:85,matchReasons:['User reviewed and entered this sold record'],mismatchWarnings:[],status:'approved',sourceTimestamp:input.soldDate,sourceMarketplace:input.marketplace,soldDate:input.soldDate,notes:input.notes}}
export const evidenceLabel=(x:ComparableEvidence)=>x.provider==='demo'?'DEMO DATA':x.evidenceType==='active-listing'?'ACTIVE ASKING PRICE':x.evidenceType==='sold-listing'?'VERIFIED SOLD COMPARABLE':x.evidenceType==='user-entered'?'USER-ENTERED SOLD COMPARABLE':'RETAIL REFERENCE';
