import{afterEach,describe,expect,it,vi}from'vitest';
import{GeminiGroundedComparableProvider,GeminiVisualIdentificationProvider,normalizeProductInput,parseVisiblePrice,validateGroundedComparables,validateIdentification}from'../gemini-provider.mjs';
const image='data:image/jpeg;base64,AA==';
describe('Gemini research providers',()=>{
 afterEach(()=>vi.restoreAllMocks());
 it('normalizes only the product image and contextual title',()=>expect(normalizeProductInput({productId:'x',title:'  Bag  ',imageDataOrUrl:image})).toMatchObject({id:'x',title:'Bag',imageDataOrUrl:image}));
 it('validates identification JSON defensively',()=>expect(validateIdentification({brand:7,material:'leather',identificationConfidence:999,searchQueries:[' query ']})).toMatchObject({brand:'',material:[],identificationConfidence:100,searchQueries:['query']}));
 it('parses only explicit visible dollar prices into integer cents',()=>{expect(parseVisiblePrice('$1,234.50')).toBe(123450);expect(parseVisiblePrice('contact seller')).toBeUndefined()});
 it('preserves grounding citations and does not invent missing prices or sold status',()=>{const r=validateGroundedComparables({comparables:[{title:'Bag',url:'https://shop.test/bag',evidenceType:'sold-listing'}]},[{url:'https://google.test/citation',title:'Citation'}]);expect(r.citations).toHaveLength(1);expect(r.comparables[0].itemPriceCents).toBeUndefined();expect(r.comparables[0].evidenceType).toBe('active-listing')});
 it('keeps products independent across requests',async()=>{const calls:any[]=[];const fetchImpl=async(_u:any,o:any)=>{calls.push(JSON.parse(o.body));return new Response(JSON.stringify({candidates:[{content:{parts:[{text:'{"comparables":[],"queriesUsed":[]}'}]},groundingMetadata:{groundingChunks:[]}}]}))};const p=new GeminiGroundedComparableProvider({apiKey:'test',fetchImpl});await Promise.all([p.search({id:'a',title:'Alpha'},{}),p.search({id:'b',title:'Beta'}, {})]);expect(JSON.stringify(calls[0])).toContain('Alpha');expect(JSON.stringify(calls[0])).not.toContain('Beta')});
 it('reports unavailable without a Gemini secret',async()=>await expect(new GeminiVisualIdentificationProvider({apiKey:''}).identify({imageDataOrUrl:image})).rejects.toMatchObject({code:'PROVIDER_UNAVAILABLE'}));
 it.each([
  [400,'GEMINI_INVALID_REQUEST',400],[401,'GEMINI_AUTHENTICATION_FAILED',401],[403,'GEMINI_PERMISSION_DENIED',403],
  [404,'GEMINI_MODEL_NOT_FOUND',404],[429,'GEMINI_RATE_LIMITED',429],[500,'GEMINI_SERVICE_UNAVAILABLE',503],[503,'GEMINI_SERVICE_UNAVAILABLE',503],
 ])('maps Gemini HTTP %i errors after reading the JSON body',async(upstreamStatus,code,status)=>{let bodyRead=false;const fetchImpl=async()=>({ok:false,status:upstreamStatus,json:async()=>{bodyRead=true;return{error:{status:'RESOURCE_EXHAUSTED',message:'Quota exceeded.',details:[{'@type':'type.googleapis.com/google.rpc.ErrorInfo',reason:'RATE_LIMIT_EXCEEDED'}]}}}} as any);await expect(new GeminiVisualIdentificationProvider({apiKey:'secret',fetchImpl,model:'safe-model'}).identify({imageDataOrUrl:image})).rejects.toMatchObject({code,status,upstreamStatus,upstreamErrorStatus:'RESOURCE_EXHAUSTED',upstreamMessage:'Quota exceeded.',upstreamReason:'RATE_LIMIT_EXCEEDED',model:'safe-model',operation:'visual-identification',guidance:expect.any(String)});expect(bodyRead).toBe(true)});
 it('redacts secrets, query parameters, images, and oversized upstream content',async()=>{const secret='AIza'+('x'.repeat(32)),prompt='P'.repeat(500),fetchImpl=async()=>new Response(JSON.stringify({error:{status:'INVALID_ARGUMENT',message:`Bad https://example.test/path?key=${secret} data:image/jpeg;base64,${'A'.repeat(100)} prompt=${prompt}`,details:[]}}),{status:400});let error:any;try{await new GeminiGroundedComparableProvider({apiKey:secret,fetchImpl}).search({id:'x',imageDataOrUrl:image},{})}catch(e){error=e}const exposed=JSON.stringify(error);expect(error).toMatchObject({code:'GEMINI_INVALID_REQUEST',operation:'grounded-comparables'});expect(exposed).not.toContain(secret);expect(exposed).not.toContain('?key=');expect(exposed).not.toContain('data:image');expect(exposed).not.toContain(prompt);expect(error.upstreamMessage.length).toBeLessThanOrEqual(300)});
 it('writes only structured safe Gemini failure metadata to Render logs',async()=>{const log=vi.spyOn(console,'error').mockImplementation(()=>{}),fetchImpl=async()=>new Response(JSON.stringify({error:{message:'denied',status:'PERMISSION_DENIED',details:[{'@type':'type.googleapis.com/google.rpc.ErrorInfo',reason:'API_KEY_SERVICE_BLOCKED'}]}}),{status:403});await expect(new GeminiVisualIdentificationProvider({apiKey:'do-not-log',fetchImpl,model:'gemini-test'}).identify({imageDataOrUrl:image})).rejects.toBeTruthy();expect(log).toHaveBeenCalledWith('[gemini]',{provider:'gemini',operation:'visual-identification',upstreamStatus:403,upstreamReason:'API_KEY_SERVICE_BLOCKED',model:'gemini-test'});expect(JSON.stringify(log.mock.calls)).not.toContain('do-not-log')});
});
