export type EvidenceType='active'|'sold'|'retail';
export type MatchQuality='exact'|'strong'|'similar'|'weak';
export type Comparable={id:string;priceCents:number;shippingCents:number;marketplace:string;evidenceType:EvidenceType;condition:string;matchQuality:MatchQuality;url?:string;notes?:string;excluded?:boolean;includeSimilar?:boolean;demo?:boolean};
export type Item={id:string;name:string;image?:string;originalImage?:string;currentBidCents:number;shippingCents:number;premiumBps:number;taxBps:number;condition:string;notes:string;otherAcquisitionCents:number;comparables:Comparable[];assumptions:Assumptions;updatedAt:string};
export type Assumptions={activeConservativeBps:number;activeExpectedBps:number;activeOptimisticBps:number;retailDiscountBps:number;marketplaceFeeBps:number;processingFeeBps:number;outboundShippingCents:number;packagingCents:number;otherSellingCents:number;minimumProfitCents:number;minimumRoiBps:number};
export const defaultAssumptions:Assumptions={activeConservativeBps:6500,activeExpectedBps:7500,activeOptimisticBps:9000,retailDiscountBps:5000,marketplaceFeeBps:1500,processingFeeBps:300,outboundShippingCents:1200,packagingCents:200,otherSellingCents:0,minimumProfitCents:2500,minimumRoiBps:3000};
const mul=(n:number,bps:number)=>Math.round(n*bps/10000);
export const approved=(c:Comparable)=>Boolean(!c.excluded&&c.matchQuality!=='weak'&&(c.matchQuality!=='similar'||c.includeSimilar));
export function resale(c:Comparable,a:Assumptions,scenario:'conservative'|'expected'|'optimistic') {const total=c.priceCents+c.shippingCents;if(c.evidenceType==='sold')return total;if(c.evidenceType==='retail')return mul(total,a.retailDiscountBps);return mul(total,scenario==='conservative'?a.activeConservativeBps:scenario==='expected'?a.activeExpectedBps:a.activeOptimisticBps)}
export function median(values:number[]){const x=[...values].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length?(x.length%2?x[m]:Math.round((x[m-1]+x[m])/2)):0}
export function calculate(item:Item){const cs=item.comparables.filter(approved),a=item.assumptions;const values=(s:'conservative'|'expected'|'optimistic')=>cs.map(c=>resale(c,a,s)).sort((x,y)=>x-y);const conservative=values('conservative')[0]||0,expected=median(values('expected')),optimistic=values('optimistic').at(-1)||0;const premium=mul(item.currentBidCents,item.premiumBps),tax=mul(item.currentBidCents+premium,item.taxBps),acquisition=item.currentBidCents+premium+tax+item.shippingCents+item.otherAcquisitionCents;const fees=mul(expected,a.marketplaceFeeBps)+mul(expected,a.processingFeeBps)+a.outboundShippingCents+a.packagingCents+a.otherSellingCents,net=expected-fees,profit=net-acquisition,roi=acquisition?Math.round(profit*10000/acquisition):0;const fixed=item.shippingCents+item.otherAcquisitionCents,rate=(10000+item.premiumBps)*(10000+item.taxBps);const bidForAcquisition=(budget:number)=>Math.max(0,Math.floor((budget-fixed)*100000000/rate));const profitMax=bidForAcquisition(net-a.minimumProfitCents);const roiMax=bidForAcquisition(Math.floor(net*10000/(10000+a.minimumRoiBps)));const maximumBid=Math.min(profitMax,roiMax),spread=conservative?optimistic/conservative:Infinity;let decision:'BUY'|'MAYBE'|'PASS'='BUY';const reasons:string[]=[];if(!cs.length){decision='PASS';reasons.push('No credible comparable evidence exists.')}else if(item.currentBidCents>maximumBid||profit<0||roi<a.minimumRoiBps){decision='PASS';reasons.push(item.currentBidCents>maximumBid?'The current bid exceeds the safe maximum.':'Profit or ROI misses your target.')}else if(cs.length===1||item.currentBidCents>=maximumBid*.85||spread>1.75){decision='MAYBE';reasons.push(cs.length===1?'Only one credible comparable is available.':spread>1.75?'Comparable prices have a wide spread.':'The bid is close to your maximum.')}else reasons.push('Profit, ROI, evidence, and bid-room targets are met.');return{conservative,expected,optimistic,acquisition,fees,profit,roi,profitMax,roiMax,maximumBid,bidRoom:maximumBid-item.currentBidCents,credibleCount:cs.length,highSpread:spread>1.75,decision,reasons}}
const DB='bidlens-local',STORE='items';
export const itemStore={async db(){return new Promise<IDBDatabase>((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})},async save(i:Item){const db=await this.db();return new Promise<void>((ok,no)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(i);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})},async get(id:string){const db=await this.db();return new Promise<Item|undefined>((ok,no)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})},async clear(){const db=await this.db();return new Promise<void>((ok,no)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).clear();r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}};
