import type{ComparableEvidence,ComparableProvider,ComparableSearchOptions,ComparableSearchResult,ResearchableProduct}from'./types';
import{generateSearchQueries,scoreComparable}from'./comparables';
const configured=()=>String(import.meta.env.VITE_COMPARABLE_API_URL||'').replace(/\/+$/,'');
export class ComparableProviderError extends Error{constructor(public code:'UNAVAILABLE'|'TIMEOUT'|'INVALID_RESPONSE'|'PROVIDER_ERROR',message:string,public retryable=false){super(message)}}
export class EbayBrowseComparableProvider implements ComparableProvider{async search(product:ResearchableProduct,options?:ComparableSearchOptions){const base=configured();if(!base)throw new ComparableProviderError('UNAVAILABLE','Comparable research unavailable');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(`${base}/api/comparables/search`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...product,productId:product.id,imageDataOrUrl:options?.imageSearch?product.imageUrl:undefined}),signal:controller.signal});if(!response.ok)throw new ComparableProviderError(response.status>=500?'PROVIDER_ERROR':'INVALID_RESPONSE','The comparable provider is temporarily unavailable.',response.status>=500);const body=await response.json() as ComparableSearchResult;if(!Array.isArray(body.results)||body.provider!=='ebay-browse')throw new ComparableProviderError('INVALID_RESPONSE','The comparable provider returned an invalid response.');return{...body,results:body.results.map(row=>normalizeProviderEvidence(product,row))}}catch(e){if(e instanceof ComparableProviderError)throw e;if(e instanceof DOMException&&e.name==='AbortError')throw new ComparableProviderError('TIMEOUT','Comparable search timed out.',true);throw new ComparableProviderError('UNAVAILABLE','Comparable research unavailable',true)}finally{clearTimeout(timer)}}}
export class GeminiGroundedComparableProvider implements ComparableProvider{async search(product:ResearchableProduct){const base=configured();if(!base)throw new ComparableProviderError('UNAVAILABLE','Provider unavailable');const response=await fetch(`${base}/api/comparables/search`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...product,productId:product.id,imageDataOrUrl:product.imageUrl})});if(!response.ok)throw new ComparableProviderError(response.status===503?'UNAVAILABLE':'PROVIDER_ERROR','Gemini research is temporarily unavailable.',response.status>=500);const body=await response.json() as any;if(!Array.isArray(body.comparables))throw new ComparableProviderError('INVALID_RESPONSE','Gemini returned an invalid response.');const results:ComparableEvidence[]=body.comparables.map((x:any,i:number)=>normalizeProviderEvidence(product,{id:`gemini-${product.id}-${i}`,productId:product.id,provider:'gemini-grounded',evidenceType:x.evidenceType==='retail-reference'?'retail-reference':'active-listing',title:x.title,url:x.url,imageUrl:x.imageUrl,itemPriceCents:x.itemPriceCents??0,totalPriceCents:x.totalPriceCents??0,priceEstablished:Number.isInteger(x.itemPriceCents),citations:body.citations||[],shippingCents:x.shippingCents,condition:x.condition,matchScore:x.matchConfidence,matchReasons:x.matchReasons||[],mismatchWarnings:x.warnings||[],status:'pending',sourceTimestamp:body.searchedAt,sourceMarketplace:x.marketplace,notes:undefined}));return Object.assign({productId:product.id,queriesUsed:body.queriesUsed||[],results,warnings:body.identification?.warnings||[],provider:'gemini-grounded' as const,searchedAt:body.searchedAt},{identification:body.identification})}
}
export class DemoComparableProvider implements ComparableProvider{constructor(private records:ComparableEvidence[]){ }async search(product:ResearchableProduct):Promise<ComparableSearchResult>{return{productId:product.id,queriesUsed:generateSearchQueries(product),results:this.records.filter(x=>x.productId===product.id).map(x=>({...x,status:'pending'})),warnings:['Demo data is illustrative and is not live marketplace evidence.'],provider:'demo',searchedAt:new Date().toISOString()}}}
export class ManualComparableProvider implements ComparableProvider{constructor(private records:ComparableEvidence[]){ }async search(product:ResearchableProduct):Promise<ComparableSearchResult>{return{productId:product.id,queriesUsed:[],results:this.records.filter(x=>x.productId===product.id&&x.provider==='manual'),warnings:[],provider:'manual',searchedAt:new Date().toISOString()}}}
export function normalizeProviderEvidence(product:ResearchableProduct,row:ComparableEvidence){const score=scoreComparable(product,row);return{...row,...score,totalPriceCents:row.itemPriceCents+(row.shippingCents||0),status:'pending' as const}}
