import { afterEach, describe, expect, it } from 'vitest';
import { createApp, normalizeCaptureError, validateCaptureUrl } from '../server.mjs';
import type { Server } from 'node:http';
let server:Server|undefined;afterEach(()=>server?.close());
async function serve(app:ReturnType<typeof createApp>){await new Promise<void>(resolve=>{server=app.listen(0,resolve)});const address=server.address();return `http://127.0.0.1:${typeof address==='object'&&address?address.port:0}`}
const publicDns=async()=>[{address:'93.184.216.34',family:4}];
describe('capture server',()=>{
 it('reports service capabilities without exposing configuration values',async()=>{const base=await serve(createApp({env:{GEMINI_API_KEY:'gemini-secret',GOOGLE_CLOUD_PROJECT:'project-secret',GOOGLE_APPLICATION_CREDENTIALS:'/secret/key.json'},captureHealth:async()=>({status:'ok'})}));const r=await fetch(`${base}/api/health`),body=await r.json();expect(r.status).toBe(200);expect(body).toMatchObject({status:'ok',service:'bidlens-api',capabilities:{geminiComparables:{available:true,reason:'configured'},capture:{available:true,reason:'Chromium available'},googleVision:{available:true,reason:'configured'}}});expect(new Date(body.timestamp).toISOString()).toBe(body.timestamp);expect(JSON.stringify(body)).not.toContain('gemini-secret');expect(JSON.stringify(body)).not.toContain('project-secret');expect(JSON.stringify(body)).not.toContain('/secret/key.json')});
 it('keeps service health ok when Chromium and optional providers are unavailable',async()=>{const base=await serve(createApp({env:{},captureHealth:async()=>{throw Object.assign(new Error('Chromium is not installed.'),{code:'BROWSER_UNAVAILABLE',status:503})}}));const r=await fetch(`${base}/api/health`);expect(r.status).toBe(200);expect(await r.json()).toMatchObject({status:'ok',capabilities:{geminiComparables:{available:false,reason:'GEMINI_API_KEY is not configured'},capture:{available:false,reason:'Chromium is not installed'},googleVision:{available:false,reason:'not configured'}}})});
 it('derives Gemini readiness only from GEMINI_API_KEY',async()=>{const captureHealth=async()=>({status:'ok'});const configured=await serve(createApp({env:{GEMINI_API_KEY:'set'},captureHealth}));expect((await (await fetch(`${configured}/api/health`)).json()).capabilities.geminiComparables).toEqual({available:true,reason:'configured'});server?.close();const missing=await serve(createApp({env:{GOOGLE_CLOUD_PROJECT:'configured-elsewhere'},captureHealth}));expect((await (await fetch(`${missing}/api/health`)).json()).capabilities.geminiComparables).toEqual({available:false,reason:'GEMINI_API_KEY is not configured'})});
 it('retains the strict Chromium check on capture health',async()=>{const base=await serve(createApp({captureHealth:async()=>{throw Object.assign(new Error('Chromium is not installed.'),{code:'BROWSER_UNAVAILABLE',status:503})}}));const r=await fetch(`${base}/api/capture/health`);expect(r.status).toBe(503);expect(await r.json()).toMatchObject({code:'BROWSER_UNAVAILABLE'})});
 it('does not check Chromium before identification or comparable research',async()=>{let browserChecks=0;const captureHealth=()=>{browserChecks++;throw new Error('browser check must not run')},identifyProvider={identify:async()=>({brand:'Test'})},searchComparables=async()=>({comparables:[]});const base=await serve(createApp({captureHealth,identifyProvider,searchComparables}));const headers={'content-type':'application/json'};const identify=await fetch(`${base}/api/identify/product`,{method:'POST',headers,body:'{}'});const comparables=await fetch(`${base}/api/comparables/search`,{method:'POST',headers,body:'{}'});expect(identify.status).toBe(200);expect(await identify.json()).toEqual({brand:'Test'});expect(comparables.status).toBe(200);expect(await comparables.json()).toEqual({comparables:[]});expect(browserChecks).toBe(0)});
 it('rejects invalid and unsupported URLs',async()=>{await expect(validateCaptureUrl('bad',publicDns)).rejects.toMatchObject({code:'INVALID_URL'});await expect(validateCaptureUrl('https://example.com',publicDns)).rejects.toMatchObject({code:'UNSUPPORTED_DOMAIN'})});
 it('rejects private DNS destinations',async()=>expect(validateCaptureUrl('https://www.ebth.com/a',async()=>[{address:'127.0.0.1',family:4}])).rejects.toMatchObject({code:'BLOCKED_DESTINATION'}));
 it('normalizes capture timeouts',()=>expect(normalizeCaptureError(new Error('page.goto: Timeout 20000ms exceeded'))).toMatchObject({code:'CAPTURE_TIMEOUT',status:408}));
 it('preserves a zero-product partial screenshot',async()=>{const result={capture:{sourceUrl:'https://www.ebth.com/a',pageTitle:'A',capturedAt:'now',width:1,height:1,status:'partial',warnings:['No products'],screenshotUrl:'data:image/jpeg;base64,AA=='},products:[],warnings:[{code:'NO_PRODUCTS_FOUND'}]};const base=await serve(createApp({capture:async()=>result}));const data=await (await fetch(`${base}/api/capture`,{method:'POST',headers:{'content-type':'application/json'},body:'{"url":"https://www.ebth.com/a"}'})).json();expect(data.capture.status).toBe('partial');expect(data.products).toEqual([])});
 it('preserves products with row warnings',async()=>{const result={capture:{status:'partial'},products:[{id:'1',extractionWarnings:['Missing bid.']}],warnings:[{code:'PARTIAL_EXTRACTION'}]};const base=await serve(createApp({capture:async()=>result}));const data=await (await fetch(`${base}/api/capture`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'})).json();expect(data.products[0].extractionWarnings).toEqual(['Missing bid.'])});
});
